// Regenerates the two vendored design assets: the icon sprite and the subset
// webfont. Both are committed, so this only needs running when the icon set or
// the character coverage changes.
//
//   npm pack lucide-static @fontsource-variable/archivo   (into some temp dir)
//   node tools/build-assets.mjs <unpacked-dir>
//
// Nothing in the app fetches from a CDN — the artifact's content policy blocks
// every external host, so fonts and icons have to live in the repo.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const src = process.argv[2];

if (!src) {
  console.error('usage: node tools/build-assets.mjs <dir containing lucide-static/ and the archivo woff2>');
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Icons -> one inline SVG sprite
// ---------------------------------------------------------------------------

// Every icon the app uses, grouped by where it earns its place.
const ICONS = [
  // tab bar
  'calendar-days', 'shopping-basket', 'chef-hat', 'tag', 'sliders-horizontal',
  // meal slots
  'sunrise', 'sandwich', 'utensils-crossed', 'apple', 'cookie',
  // shop aisles
  'beef', 'egg', 'carrot', 'snowflake', 'croissant', 'soup',
  // actions and state
  'chevron-left', 'chevron-right', 'check', 'x', 'plus', 'search', 'camera',
  'triangle-alert', 'info', 'refresh-cw', 'trash-2', 'timer', 'flame', 'pencil',
];

function buildSprite() {
  const symbols = ICONS.map((name) => {
    const file = join(src, 'lucide-static', 'icons', `${name}.svg`);
    const svg = readFileSync(file, 'utf8');
    // Keep the drawing, drop lucide's own <svg> wrapper — stroke settings move
    // to CSS so a single sprite can be recoloured and resized by context.
    const inner = svg
      .replace(/<svg[^>]*>/, '')
      .replace(/<\/svg>\s*$/, '')
      .replace(/\s+/g, ' ')
      .trim();
    return `<symbol id="i-${name}" viewBox="0 0 24 24">${inner}</symbol>`;
  }).join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">${symbols}</svg>`;
}

const sprite = buildSprite();

writeFileSync(join(root, 'js', 'icons.js'), `// GENERATED by tools/build-assets.mjs — do not edit by hand.
//
// Lucide icons (ISC), inlined as one SVG sprite. Every glyph in the app comes
// from here: emoji render differently on every phone and can't take the theme's
// colour, and both matter in an interface that's mostly small labels.

export const ICON_NAMES = ${JSON.stringify(ICONS)};

export const SPRITE = ${JSON.stringify(sprite)};

// Strokes inherit currentColor, so an icon takes the colour of the text it sits
// in and needs no per-use styling.
export function icon(name, cls = '') {
  return \`<svg class="ico \${cls}" aria-hidden="true"><use href="#i-\${name}"></use></svg>\`;
}

// Injected once at boot; <use> can only reach a sprite that's in the document.
export function mountSprite() {
  if (document.getElementById('icon-sprite')) return;
  const holder = document.createElement('div');
  holder.id = 'icon-sprite';
  holder.innerHTML = SPRITE;
  document.body.appendChild(holder);
}
`);

console.log(`icons: ${ICONS.length} symbols -> js/icons.js (${Math.round(sprite.length / 1024)} KB)`);

// ---------------------------------------------------------------------------
// Font -> subset woff2 kept as a binary in the repo
// ---------------------------------------------------------------------------

// Latin, plus the punctuation this app actually sets: £ · × ½ ¼ – — ' " … ‹ › ✓
const UNICODES = 'U+0020-007E,U+00A0-00FF,U+2013-2014,U+2018-201D,U+2022,U+2026,U+2039-203A,U+2044,U+2192,U+2713,U+2715';

const fontIn = join(src, 'lucide-static', 'files', 'archivo-latin-standard-normal.woff2');
const fontOut = join(root, 'fonts', 'archivo-subset.woff2');

if (existsSync(fontIn)) {
  mkdirSync(join(root, 'fonts'), { recursive: true });
  execFileSync('pyftsubset', [
    fontIn, `--output-file=${fontOut}`, '--flavor=woff2',
    '--layout-features=*',            // keeps tabular figures and kerning
    `--unicodes=${UNICODES}`,
  ]);
  const size = readFileSync(fontOut).length;
  console.log(`font: archivo variable (wght 100-900, wdth 62-125) -> fonts/archivo-subset.woff2 (${Math.round(size / 1024)} KB)`);
} else {
  console.log('font: source woff2 not found, left as is');
}
